[package]
name = "leucli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockall = "0.12.1"
serde_json = "1.0.113"
serial_test = "2.0.0"
simple-home-dir = "0.3.2"

[build]
target = "debug"
